export const BEGIN_FETCH_CALL = "BEGIN_FETCH_CALL";
export const FETCH_ERROR_CALL = "FETCH_ERROR_CALL";

export const LOAD_APPLICATION_SUCCESS = "LOAD_APPLICATION_SUCCESS";
export const ADD_APPLICATION_SUCCESS = "ADD_APPLICATION_SUCCESS";
